# Generated by Django 5.0.14 on 2026-04-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meli_category_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meli_condition',
            field=models.CharField(choices=[('new', 'Nuevo'), ('used', 'Usado'), ('not_specified', 'No especificado')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='meli_listing_type',
            field=models.CharField(choices=[('gold_special', 'Premium'), ('gold_pro', 'Clásica'), ('silver', 'Plata'), ('bronze', 'Bronce')], default='gold_special', max_length=30),
        ),
    ]
