# Generated by Django 5.0.14 on 2026-04-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_brand_product_dimensions_product_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meli_category_id',
            field=models.CharField(blank=True, help_text='ID de categoría equivalente en Mercado Libre', max_length=20, null=True),
        ),
    ]
