# Generated by Django 6.0.3 on 2026-05-05 21:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_category_meli_category_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('price_retail', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_wholesale', models.DecimalField(decimal_places=2, help_text='Precio para clientes Gremio/Distribuidor', max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_current', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ecommerce', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('meli_item_id', models.CharField(blank=True, max_length=50, null=True)),
                ('meli_sync', models.BooleanField(default=False)),
                ('meli_category_id', models.CharField(blank=True, max_length=20, null=True)),
                ('meli_condition', models.CharField(choices=[('new', 'Nuevo'), ('used', 'Usado'), ('not_specified', 'No especificado')], default='new', max_length=20)),
                ('meli_listing_type', models.CharField(choices=[('gold_special', 'Premium'), ('gold_pro', 'Clásica'), ('silver', 'Plata'), ('bronze', 'Bronce')], default='gold_special', max_length=30)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
