# Generated by Django 6.0.5 on 2026-06-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_historicalproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Orden de aparición en la tienda (menor = primero)'),
        ),
    ]
