# Generated by Django 5.0.3 on 2026-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_catalog_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='stock_pushed_at',
            field=models.DateTimeField(blank=True, help_text='Última versión de stock confirmada como subida al Google Sheet', null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='stock_updated_at',
            field=models.DateTimeField(blank=True, help_text='Último cambio de stock hecho en la web', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_pushed_at',
            field=models.DateTimeField(blank=True, help_text='Última versión de stock confirmada como subida al Google Sheet', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_updated_at',
            field=models.DateTimeField(blank=True, help_text='Último cambio de stock hecho en la web', null=True),
        ),
    ]
