# Generated by Django 5.0.3 on 2026-10-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_historicalproduct_stock_pushed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
