# Generated by Django 6.0.3 on 2026-05-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mi Ferretería', max_length=100)),
                ('store_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('afip_cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_cvu', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_alias', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mp_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('mp_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('mp_refresh_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
