# Generated by Django 5.0.14 on 2026-06-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_storeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='afip_certificate',
            field=models.FileField(blank=True, null=True, upload_to='afip/'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='afip_private_key',
            field=models.FileField(blank=True, null=True, upload_to='afip/'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='afip_punto_venta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
