# Generated by Django 5.0.3 on 2026-06-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_storeconfig_afip_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconfig',
            name='afip_certificate',
        ),
        migrations.RemoveField(
            model_name='storeconfig',
            name='afip_cuit',
        ),
        migrations.RemoveField(
            model_name='storeconfig',
            name='afip_private_key',
        ),
        migrations.RemoveField(
            model_name='storeconfig',
            name='afip_punto_venta',
        ),
    ]
