# Generated by Django 5.0.3 on 2026-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_storeconfig_afip_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='store_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
