# Generated by Django 5.0.3 on 2026-07-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_storeconfig_facebook_url_storeconfig_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='bank_cuit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='bank_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
