# Generated by Django 5.0.3 on 2026-09-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_storeconfig_bank_cuit_storeconfig_bank_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconfig',
            name='name',
            field=models.CharField(default='Tierra Verde Grow', max_length=100),
        ),
    ]
