# Generated by Django 6.0.3 on 2026-05-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('MELI', 'Mercado Libre'), ('AFIP', 'AFIP'), ('CORREO_ARG', 'Correo Argentino')], max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('afip_cuit', models.CharField(blank=True, max_length=11, null=True)),
                ('afip_cert', models.TextField(blank=True, null=True)),
                ('afip_key', models.TextField(blank=True, null=True)),
                ('is_production', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('integration_type',)},
            },
        ),
    ]
