# Generated by Django 5.0.3 on 2026-06-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationconfig',
            name='afip_cert',
        ),
        migrations.RemoveField(
            model_name='integrationconfig',
            name='afip_cuit',
        ),
        migrations.RemoveField(
            model_name='integrationconfig',
            name='afip_key',
        ),
        migrations.RemoveField(
            model_name='integrationconfig',
            name='is_production',
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='integration_type',
            field=models.CharField(choices=[('MELI', 'Mercado Libre'), ('CORREO_ARG', 'Correo Argentino')], max_length=20),
        ),
    ]
