# Generated by Django 5.0.3 on 2026-07-24 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_remove_integrationconfig_afip_cert_and_more'),
        ('inventory', '0007_alter_category_options_category_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('MELI', 'Mercado Libre'), ('FACEBOOK', 'Facebook Marketplace')], max_length=20)),
                ('channel_publication_id', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente'), ('PUBLISHED', 'Publicado'), ('ERROR', 'Error'), ('REMOVED', 'Eliminado')], default='DRAFT', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'channel')},
            },
        ),
    ]
