# Generated by Django 5.0.3 on 2026-09-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_productpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfig',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
