# Generated by Django 5.0.3 on 2026-09-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_integrationconfig_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='integration_type',
            field=models.CharField(choices=[('MELI', 'Mercado Libre'), ('CORREO_ARG', 'Correo Argentino'), ('GOOGLE_SHEETS', 'Google Sheets')], max_length=20),
        ),
    ]
