# Generated by Django 5.0.3 on 2026-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
