from django.core.management.base import BaseCommand
from apps.inventory.models import Category, Product


CATEGORIES = [
    {
        "name": "Herramientas Electricas",
        "display_order": 1,
        "products": [
            {
                "name": "Taladro Percutor Inalámbrico 20V",
                "sku": "HE-TAL-001",
                "description": "Taladro percutor inalámbrico con 2 velocidades, mandril de 13mm y 20+1 torque. Incluye 2 baterías de litio y cargador. Ideal para trabajos de perforación en madera, metal y mampostería.",
                "price_retail": 45999,
                "price_wholesale": 38999,
                "cost_price": 28000,
                "stock_current": 25,
                "brand": "DeWalt",
                "material": "Acero reforzado / ABS",
                "weight": "1.8 kg",
                "dimensions": "380 x 100 x 250 mm",
                "warranty": "3 años",
                "discount_percentage": 15,
                "featured": True,
            },
            {
                "name": "Amoladora Angular 4.5 pulgadas",
                "sku": "HE-AMO-002",
                "description": "Amoladora angular de 720W con disco de 115mm, protección anti-rearranque y guardas ajustables. Perfecta para corte y desbaste de metal, cerámica y piedra.",
                "price_retail": 32999,
                "price_wholesale": 27999,
                "cost_price": 19500,
                "stock_current": 18,
                "brand": "Bosch",
                "material": "Acero / Poliamida reforzada",
                "weight": "2.1 kg",
                "dimensions": "370 x 130 x 120 mm",
                "warranty": "2 años",
                "discount_percentage": 10,
                "featured": True,
            },
            {
                "name": "Sierra Circular 7.25 pulgadas",
                "sku": "HE-SIE-003",
                "description": "Sierra circular de 1400W con guía láser, corte inclinado hasta 55° y profundidad de corte de 65mm. Base de aluminio estampada para cortes precisos.",
                "price_retail": 67999,
                "price_wholesale": 57999,
                "cost_price": 42000,
                "stock_current": 12,
                "brand": "Makita",
                "material": "Aluminio / Acero",
                "weight": "4.2 kg",
                "dimensions": "450 x 350 x 280 mm",
                "warranty": "2 años",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Lijadora Orbital 5 pulgadas",
                "sku": "HE-LIJ-004",
                "description": "Lijadora orbital de 300W con velocidad variable 6000-12000 RPM, colector de polvo integrado y base de 125mm. Para acabado fino en madera y metales.",
                "price_retail": 24999,
                "price_wholesale": 21999,
                "cost_price": 15000,
                "stock_current": 30,
                "brand": "Black+Decker",
                "material": "ABS / Aluminio",
                "weight": "1.4 kg",
                "dimensions": "300 x 160 x 130 mm",
                "warranty": "1 año",
                "discount_percentage": 20,
                "featured": False,
            },
            {
                "name": "Rotomartillo SDS Plus 800W",
                "sku": "HE-ROT-005",
                "description": "Rotomartillo con sistema SDS Plus, 3 funciones (taladro, percutor, martillo), 800W y 3000 impactos/min. Incluye juego de 5 brocas y funda.",
                "price_retail": 58999,
                "price_wholesale": 49999,
                "cost_price": 35000,
                "stock_current": 10,
                "brand": "Bosch",
                "material": "Acero endurecido / Fibra de vidrio",
                "weight": "2.8 kg",
                "dimensions": "420 x 110 x 230 mm",
                "warranty": "2 años",
                "discount_percentage": 5,
                "featured": True,
            },
            {
                "name": "Caladora 700W",
                "sku": "HE-CAL-006",
                "description": "Caladora de 700W con guía láser, base oscilante y velocidad variable. Corte de curvas en madera, metal plástico y cerámica. Incluye 3 sierras.",
                "price_retail": 28999,
                "price_wholesale": 24999,
                "cost_price": 17000,
                "stock_current": 22,
                "brand": "Makita",
                "material": "Aluminio / ABS",
                "weight": "1.9 kg",
                "dimensions": "350 x 140 x 160 mm",
                "warranty": "2 años",
                "discount_percentage": 0,
                "featured": False,
            },
        ],
    },
    {
        "name": "Plomeria",
        "display_order": 2,
        "products": [
            {
                "name": "Llave de Paso 1/2 cromada",
                "sku": "PL-LLV-001",
                "description": "Llave de paso cromada de 1/2 pulgada con bola cerámica, cuerpo de latón cromado. Para agua caliente y fría. Alta durabilidad y sellado perfecto.",
                "price_retail": 8999,
                "price_wholesale": 7499,
                "cost_price": 4500,
                "stock_current": 50,
                "brand": "Rapier",
                "material": "Latón cromado",
                "weight": "0.35 kg",
                "dimensions": "180 x 60 x 30 mm",
                "warranty": "5 años",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Cinta Teflón Selladora 12mm x 10m",
                "sku": "PL-CTF-002",
                "description": "Cinta de teflón selladora de alta densidad 12mm x 10 metros, resistente a altas temperaturas y presiones. Ideal para roscas de cañerías de agua.",
                "price_retail": 1299,
                "price_wholesale": 999,
                "cost_price": 450,
                "stock_current": 200,
                "brand": "Anaconda",
                "material": "PTFE",
                "weight": "0.02 kg",
                "dimensions": "12mm x 10m",
                "warranty": "Sin limite",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Grifo Lavatorio Cromado",
                "sku": "PL-GRF-003",
                "description": "Grifo monocomando para lavatorio con acabado cromado, cuerpo de latón y cartucho cerámico. Ahorro de agua certificado. Fácil instalación.",
                "price_retail": 19999,
                "price_wholesale": 16999,
                "cost_price": 11000,
                "stock_current": 35,
                "brand": "Fv",
                "material": "Latón cromado",
                "weight": "1.2 kg",
                "dimensions": "160 x 120 x 60 mm",
                "warranty": "3 años",
                "discount_percentage": 10,
                "featured": True,
            },
            {
                "name": "Tubería PVC 25mm x 3m",
                "sku": "PL-TUB-004",
                "description": "Tubería de PVC sanitario de 25mm, 3 metros de largo, clase 10 (10 atmósferas). Para instalaciones de agua fría y caliente. Norma IRAM.",
                "price_retail": 2499,
                "price_wholesale": 1999,
                "cost_price": 1200,
                "stock_current": 150,
                "brand": "Tersa",
                "material": "PVC",
                "weight": "0.45 kg",
                "dimensions": "25mm x 3000mm",
                "warranty": "10 años",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Llave Inglesa 12 pulgadas",
                "sku": "PL-ING-005",
                "description": "Llave inglesa ajustable de 12 pulgadas con boca de 0-35mm, acabado cromado y mango antideslizante. Trabajo pesado y ajuste preciso.",
                "price_retail": 7999,
                "price_wholesale": 6799,
                "cost_price": 4200,
                "stock_current": 40,
                "brand": "Tramontina",
                "material": "Acero cromado",
                "weight": "0.65 kg",
                "dimensions": "310 x 75 x 25 mm",
                "warranty": "2 años",
                "discount_percentage": 5,
                "featured": False,
            },
            {
                "name": "Sifón Flexible 32mm cromado",
                "sku": "PL-SIF-006",
                "description": "Sifón flexible plástico con acabado cromado de 32mm para desagüe de lavatorio. Fácil instalación sin herramientas. Anti-olores.",
                "price_retail": 3999,
                "price_wholesale": 3299,
                "cost_price": 1800,
                "stock_current": 60,
                "brand": "Anaconda",
                "material": "PVC / Cromado",
                "weight": "0.15 kg",
                "dimensions": "32mm x 350mm",
                "warranty": "1 año",
                "discount_percentage": 0,
                "featured": False,
            },
        ],
    },
    {
        "name": "Pintureria",
        "display_order": 3,
        "products": [
            {
                "name": "Pintura Sintética Blanca 20L",
                "sku": "PT-SIN-001",
                "description": "Pintura sintética esmalte blanco brillante de alta cobertura, 20 litros. Resistente a la intemperie, lavable y de secado rápido. Rinde 8-10 m²/L.",
                "price_retail": 38999,
                "price_wholesale": 33999,
                "cost_price": 24000,
                "stock_current": 20,
                "brand": "Tintas del Sur",
                "material": "Base solvente",
                "weight": "22 kg",
                "dimensions": "Ø 300 x 400 mm",
                "warranty": "5 años en fachada",
                "discount_percentage": 10,
                "featured": True,
            },
            {
                "name": "Rodillo Látex 23cm con Mango",
                "sku": "PT-ROL-002",
                "description": "Rodillo de pelaje de látex 11mm para interiores, 23cm de ancho con mango telescópico extensible hasta 2 metros. Acabado liso y uniforme.",
                "price_retail": 4599,
                "price_wholesale": 3799,
                "cost_price": 2200,
                "stock_current": 80,
                "brand": "Roly",
                "material": "Látex / Acero",
                "weight": "0.3 kg",
                "dimensions": "230 x 60 x 60 mm",
                "warranty": "6 meses",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Brocha 4 pulgadas Cerda Natural",
                "sku": "PT-BRC-003",
                "description": "Brocha de 4 pulgadas con cerda natural para pinturas base solvente. Mango de madera ergonómico. Carga y distribución uniforme de pintura.",
                "price_retail": 3299,
                "price_wholesale": 2699,
                "cost_price": 1500,
                "stock_current": 100,
                "brand": "Roly",
                "material": "Cerda natural / Madera",
                "weight": "0.12 kg",
                "dimensions": "100 x 30 x 220 mm",
                "warranty": "3 meses",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Masilla Reparadora Interior 1kg",
                "sku": "PT-MAS-004",
                "description": "Masilla acrílica para relleno y reparación de grietas y agujeros en paredes interiores. Secado rápido, lijable y pintable. Cubre hasta 2m².",
                "price_retail": 2999,
                "price_wholesale": 2499,
                "cost_price": 1300,
                "stock_current": 45,
                "brand": "Sinteplast",
                "material": "Base acrílica",
                "weight": "1 kg",
                "dimensions": "150 x 150 x 100 mm",
                "warranty": "1 año",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Sellador Multi-superficies 300ml",
                "sku": "PT-SLD-005",
                "description": "Sellador acrílico multiusos para grietas en techos, paredes y pisos. Elástico, pintable y resistente al agua. Kartucho de 300ml compatible con pistola.",
                "price_retail": 2199,
                "price_wholesale": 1799,
                "cost_price": 900,
                "stock_current": 70,
                "brand": "Loctite",
                "material": "Acrílico",
                "weight": "0.4 kg",
                "dimensions": "50 x 50 x 230 mm",
                "warranty": "Sin garantía",
                "discount_percentage": 15,
                "featured": False,
            },
            {
                "name": "Imprimación Fija Alcohol 4L",
                "sku": "PT-IMR-006",
                "description": "Fijador de bases alcalinas para muros nuevos. Prepara superficies de hormigón, block y yeso antes de pintar. Mejora adherencia y reduce absorbencia.",
                "price_retail": 6999,
                "price_wholesale": 5999,
                "cost_price": 3800,
                "stock_current": 30,
                "brand": "Sinteplast",
                "material": "Base alcohol",
                "weight": "3.5 kg",
                "dimensions": "Ø 180 x 250 mm",
                "warranty": "Sin garantía",
                "discount_percentage": 5,
                "featured": True,
            },
        ],
    },
    {
        "name": "Materiales de Construccion",
        "display_order": 4,
        "products": [
            {
                "name": "Cemento Portland 50kg",
                "sku": "MC-CPT-001",
                "description": "Cemento Portland CPN 40 de alta resistencia, bolsa de 50kg. Para obras generales, contrapisos, columnas y estructuras. Cumple norma IRAM 50000.",
                "price_retail": 5999,
                "price_wholesale": 5299,
                "cost_price": 3800,
                "stock_current": 200,
                "brand": "Loma Negra",
                "material": "Clínker de cemento",
                "weight": "50 kg",
                "dimensions": "600 x 400 x 100 mm",
                "warranty": "Sin garantía",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Ladrillo Hueco 18x18x18",
                "sku": "MC-LAD-002",
                "description": "Ladrillo hueco cerámico 18x18x18cm para muros divisores y cerramientos. Alta resistencia, baja absorción. Módulo de 30 unidades por m².",
                "price_retail": 399,
                "price_wholesale": 349,
                "cost_price": 220,
                "stock_current": 5000,
                "brand": "Cerámica del Sur",
                "material": "Arcilla cocida",
                "weight": "3.2 kg",
                "dimensions": "180 x 180 x 180 mm",
                "warranty": "Sin garantía",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Arena Fina Granulado 0/2 1m³",
                "sku": "MC-ARE-003",
                "description": "Arena natural fina granulada 0/2 mm, metro cúbico a granel. Para preparación de morteros, contrapisos y mezclas de albañilería.",
                "price_retail": 12999,
                "price_wholesale": 11499,
                "cost_price": 7500,
                "stock_current": 15,
                "brand": "La Riojana",
                "material": "Arena natural",
                "weight": "1600 kg",
                "dimensions": "1 metro cúbico",
                "warranty": "Sin garantía",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Placa Durlock 12.5mm 1.2x2.4m",
                "sku": "MC-DUR-004",
                "description": "Placa de yeso cartonado Durlock standard 12.5mm, 1.20 x 2.40 metros. Para revestimiento de techos y paredes. Resistente al fuego.",
                "price_retail": 4499,
                "price_wholesale": 3899,
                "cost_price": 2600,
                "stock_current": 80,
                "brand": "Durlock",
                "material": "Yeso cartonado",
                "weight": "18 kg",
                "dimensions": "1200 x 2400 x 12.5 mm",
                "warranty": "Sin garantía",
                "discount_percentage": 0,
                "featured": True,
            },
            {
                "name": "Hierro de Refuerzo 6mm x 12m",
                "sku": "MC-HRR-005",
                "description": "Barra de acero de refuerzo deformada de 6mm de diámetro x 12 metros de largo. Para columnas, vigas y sobrecimientos. Acerostructural grado 420.",
                "price_retail": 3999,
                "price_wholesale": 3499,
                "cost_price": 2700,
                "stock_current": 100,
                "brand": "Acindar",
                "material": "Acero estructural",
                "weight": "2.66 kg/m",
                "dimensions": "6mm x 12000mm",
                "warranty": "Sin garantía",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Contrapiso Autonivelante 25kg",
                "sku": "MC-CTP-006",
                "description": "Contrapiso autonivelante de secado rápido, bolsa de 25kg. Nivelación de pisos de hasta 10mm. Compatible con cerámicos, madera y vinílicos.",
                "price_retail": 8999,
                "price_wholesale": 7999,
                "cost_price": 5500,
                "stock_current": 25,
                "brand": "Ardex",
                "material": "Base cemento",
                "weight": "25 kg",
                "dimensions": "Bolsa 400x600 mm",
                "warranty": "1 año",
                "discount_percentage": 10,
                "featured": False,
            },
        ],
    },
    {
        "name": "Electricidad",
        "display_order": 5,
        "products": [
            {
                "name": "Cable Unipolar 2.5mm x 100m",
                "sku": "EL-CBL-001",
                "description": "Cable eléctrico unipolar de cobre 2.5mm² aislado en PVC, rollo de 100 metros. Para instalaciones domiciliarias, tomacorrientes y circuitos generales.",
                "price_retail": 14999,
                "price_wholesale": 12999,
                "cost_price": 9000,
                "stock_current": 40,
                "brand": "Vialux",
                "material": "Cobre / PVC",
                "weight": "3.2 kg",
                "dimensions": "2.5mm² x 100m",
                "warranty": "10 años",
                "discount_percentage": 5,
                "featured": True,
            },
            {
                "name": "Llave Térmica 2x20A Monopolar",
                "sku": "EL-LTH-002",
                "description": "Llave térmica monopolar de 2x20 amperes, curva C. Protección contra cortocircuitos y sobrecargas. Encaje DIN estándar para tablero.",
                "price_retail": 4999,
                "price_wholesale": 4199,
                "cost_price": 2800,
                "stock_current": 60,
                "brand": "Schneider",
                "material": "Termoplástico ignífugo",
                "weight": "0.12 kg",
                "dimensions": "1模块 DIN",
                "warranty": "5 años",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Luminaria LED Panel 60x60 40W",
                "sku": "EL-PAN-003",
                "description": "Panel LED cuadrado 60x60cm de 40W, 4000 lúmenes, luz blanca neutra 4000K. Para techos de oficinas, locales y hogar. Bajo consumo.",
                "price_retail": 15999,
                "price_wholesale": 13499,
                "cost_price": 9500,
                "stock_current": 20,
                "brand": "Philips",
                "material": "Aluminio / Policarbonato",
                "weight": "1.8 kg",
                "dimensions": "600 x 600 x 12 mm",
                "warranty": "3 años",
                "discount_percentage": 15,
                "featured": True,
            },
            {
                "name": "Caño Conduit 25mm x 3m",
                "sku": "EL-CNO-004",
                "description": "Caño conduit eléctrico corrugado de 25mm x 3 metros, autoextinguible. Para canalización oculta y expuesta de cables eléctricos.",
                "price_retail": 1999,
                "price_wholesale": 1699,
                "cost_price": 900,
                "stock_current": 120,
                "brand": "Canalux",
                "material": "PVC autoextinguible",
                "weight": "0.25 kg",
                "dimensions": "25mm x 3000mm",
                "warranty": "Sin garantía",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Gabinete Tablero 12 Circuitos",
                "sku": "EL-GAB-005",
                "description": "Gabinete empotrado para tablero eléctrico de 12 circuitos con tapa metálica. Compatible con llaves térmicas y diferenciales estándar DIN.",
                "price_retail": 12999,
                "price_wholesale": 10999,
                "cost_price": 7500,
                "stock_current": 15,
                "brand": "Schneider",
                "material": "Hierro / Termoplástico",
                "weight": "3.5 kg",
                "dimensions": "400 x 300 x 90 mm",
                "warranty": "5 años",
                "discount_percentage": 0,
                "featured": False,
            },
            {
                "name": "Ficha Enchufe 2P+T 10A",
                "sku": "EL-FIC-006",
                "description": "Ficha enchufe macho polarizada 2 polos + tierra, 10 amperes. Aprobada IRAM. Para cables flexibles de 0.5 a 2.5mm². Cuerpo aislante.",
                "price_retail": 1499,
                "price_wholesale": 1199,
                "cost_price": 600,
                "stock_current": 150,
                "brand": "Lap",
                "material": "Termoplástico",
                "weight": "0.05 kg",
                "dimensions": "60 x 40 x 30 mm",
                "warranty": "2 años",
                "discount_percentage": 0,
                "featured": False,
            },
        ],
    },
]


class Command(BaseCommand):
    help = "Carga las 5 categorías más vendidas con 6 productos cada una"

    def handle(self, *args, **options):
        created_cats = 0
        created_prods = 0
        updated_prods = 0

        for cat_data in CATEGORIES:
            category, created = Category.objects.get_or_create(
                name=cat_data["name"],
                defaults={
                    "display_order": cat_data["display_order"],
                },
            )
            if created:
                created_cats += 1
                self.stdout.write(f"  + Categoría: {category.name}")

            for prod_data in cat_data["products"]:
                product, was_created = Product.objects.get_or_create(
                    sku=prod_data["sku"],
                    defaults={
                        "category": category,
                        "name": prod_data["name"],
                        "description": prod_data["description"],
                        "price_retail": prod_data["price_retail"],
                        "price_wholesale": prod_data["price_wholesale"],
                        "cost_price": prod_data["cost_price"],
                        "stock_current": prod_data["stock_current"],
                        "stock_min": 5,
                        "is_active": True,
                        "is_ecommerce": True,
                        "featured": prod_data.get("featured", False),
                        "brand": prod_data.get("brand", ""),
                        "material": prod_data.get("material", ""),
                        "weight": prod_data.get("weight", ""),
                        "dimensions": prod_data.get("dimensions", ""),
                        "warranty": prod_data.get("warranty", ""),
                        "discount_percentage": prod_data.get("discount_percentage", 0),
                    },
                )
                if was_created:
                    created_prods += 1
                    self.stdout.write(f"    + Producto: {product.name}")
                else:
                    updated_prods += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"\nListo: {created_cats} categorías nuevas, "
                f"{created_prods} productos nuevos, {updated_prods} ya existían."
            )
        )
