# Generated by Django 6.0.3 on 2026-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_historicalsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='shipping_status',
            field=models.CharField(choices=[('PENDING', 'No enviado'), ('SHIPPED', 'Enviado')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_status',
            field=models.CharField(choices=[('PENDING', 'No enviado'), ('SHIPPED', 'Enviado')], default='PENDING', max_length=20),
        ),
    ]
