# Generated by Django 5.0.3 on 2026-06-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='cae',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='cae_vencimiento',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='invoice_type',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='is_invoiced',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cae',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cae_vencimiento',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='invoice_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_invoiced',
        ),
    ]
